services:
  app:
    build: .
    image: vd-app:latest
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost
    ports:
      - "8080:80"
    volumes:
      - ./docker/php/opcache.prod.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - storage-data:/var/www/html/storage
      # (si usas subidas en public/uploads)
      # - uploads-data:/var/www/html/public/uploads

volumes:
  storage-data:
